### ISSUE TITLE
Core dumps with neovim under certain conditions

### ISSUE THREAD

**Issue by mikehaertl** [victorhqc/tree-sitter-prisma#34]
This issue was initially reported to neovim-treesitter here: https://github.com/nvim-treesitter/nvim-treesitter/issues/2979. But the stack trace seems to point to an issue with the parser so re-reporting it here.

### Describe the bug

When I edit  prisma files neovim sometimes crashes with a core dump.

### To Reproduce

1. Edit a prisma file (see below for my example)
2. Yank line 24 ( `id          Int       @id @default(autoincrement())` in the `User` model)
3. Paste the line at the end of the file

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model Link {
  id          Int       @id @default(autoincrement())
  createdAt   DateTime  @default(now())
  description String
  url         String
  postedBy    User?     @relation(fields: [postedById], references: [id])
  postedById  Int?
  votes       Vote[]
}

model User {
  id          Int       @id @default(autoincrement())
  name        String
  email       String    @unique
  password    String
  links       Link[]
  votes       Vote[]
}
```

**Comment by victorhqc** [comment]
Hello! Thank you for reporting the issue. I'll take a look, looks like some issue in the parser.

**Comment by mikehaertl** [comment]
Thanks. Can you somehow reproduce the issue? I found that it already happens for the simplest example like this:

```prisma
model User {
  id  Int  @id
}
```
When I copy the middle line and paste it at the end it crashes.

**Comment by victorhqc** [comment]
Hey @mikehaertl the issue should be resolved, I was able to reproduce something similar locally, not a `core_dump`, but I did hang infinitely. The latest release (1.2.2) should fix the problem.

Let me know if you find something else! Thanks again for reporting.

**Comment by seshotake** [comment]
I don't think that it was fixed. I was trying to reproduce this in helix-editor/helix#2703 too, but even with master branch there is still segmentation fault.

**Comment by mikehaertl** [comment]
@victorhqc I just tried and could not reproduce the issue anymore, thanks.

@seshotake Can you give an example that causes issues? Then I can try to reproduce it with neovim.

**Comment by mikehaertl** [comment]
@victorhqc Sorry, I was too quick. The example code from the comment above now works.

But then I tried wie a slightly more complex example and got a segmentation fault again. I found that I don't even have to copy anything:

```prisma
model User {
  id          Int       @id @default(autoincrement())
}
  id          Int       @id @default(autoincrement())
```

If I paste this into a file (with another editor) and try to open it with neovim it immediately crashes.

**Comment by victorhqc** [comment]
Aha, then there are probably more reasons for it, thanks! I'll take a look.

**Comment by victorhqc** [comment]
@mikehaertl can you check again with [this branch](https://github.com/victorhqc/tree-sitter-prisma/pull/39)? Maybe with some other cases could still happen, but I'm not sure.

**Comment by mikehaertl** [comment]
Looks better now. I played around a bit and had no crashes so far. Thank you.
